### ISSUE TITLE
tracebak

### ISSUE THREAD

**Issue by rodri2202** [Pymmdrza/EthereumMnemonicCrack#11]
Traceback (most recent call last):
  File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/urllib3/response.py", line 761, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/urllib3/response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/urllib3/response.py", line 765, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/urllib3/response.py", line 816, in read_chunked
    with self._error_catcher():
  File "/nix/store/8w6mm5q1n7i7cs1933im5vkbgvjlglfn-python3-3.10.13/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/Ashei/main.py", line 77, in <module>
    mmdrza()
  File "/home/runner/Ashei/main.py", line 54, in mmdrza
    balance(addr)) + '[/][gold1]             Transaction : ' + '[/][aquamarine1]' + str(
  File "<string>", line 16, in balance
  File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/requests/sessions.py", line 747, in send
    r.content
  File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

**Comment by Pymmdrza** [comment]
> Traceback (most recent call last): File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/urllib3/response.py", line 761, in _update_chunk_length self.chunk_left = int(line, 16) ValueError: invalid literal for int() with base 16: b''
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/urllib3/response.py", line 444, in _error_catcher yield File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/urllib3/response.py", line 828, in read_chunked self._update_chunk_length() File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/urllib3/response.py", line 765, in _update_chunk_length raise InvalidChunkLength(self, line) urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/requests/models.py", line 816, in generate yield from self.raw.stream(chunk_size, decode_content=True) File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/urllib3/response.py", line 624, in stream for line in self.read_chunked(amt, decode_content=decode_content): File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/urllib3/response.py", line 816, in read_chunked with self._error_catcher(): File "/nix/store/8w6mm5q1n7i7cs1933im5vkbgvjlglfn-python3-3.10.13/lib/python3.10/contextlib.py", line 153, in **exit** self.gen.throw(typ, value, traceback) File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/urllib3/response.py", line 461, in _error_catcher raise ProtocolError("Connection broken: %r" % e, e) urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/runner/Ashei/main.py", line 77, in mmdrza() File "/home/runner/Ashei/main.py", line 54, in mmdrza balance(addr)) + '[/][gold1] Transaction : ' + '[/][aquamarine1]' + str( File "", line 16, in balance File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/requests/sessions.py", line 602, in get return self.request("GET", url, **kwargs) File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/requests/sessions.py", line 747, in send r.content File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/requests/models.py", line 899, in content self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b"" File "/home/runner/Ashei/.pythonlibs/lib/python3.10/site-packages/requests/models.py", line 818, in generate raise ChunkedEncodingError(e) requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

## Use New Version 

Auto Run V4: [AutoRun_V4.bat](https://github.com/Pymmdrza/EthereumMnemonicCrack/blob/mainx/AutoRun_V4.bat)
